[project]
name = "land-reader"
version = "0.1.0"
description = "读取转换电池循环仪蓝电设备文件，一种数据提取的新思路。"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
